### ISSUE TITLE
IE11 and Safari9 hang when running test on SauceLabs

### ISSUE THREAD

**Issue by rogozinds** [Polymer/web-component-tester#550]
IE11 and Safari9 hang when running test on SauceLabs. The browser tries to open the tested web page, but instead just hangs, and afterwards fails with a timeout Error. 

Bower dependencies version:
`
  "dependencies": {
    "polymer": "^2.0.0"
  },
  "devDependencies": {
    "web-component-tester": "^6.0.0 ",
    "webcomponentsjs": "^1.0.0",
    "test-fixture": "^3.0.0-rc.1"
  }
`
...

Contents of `wct.conf.js` file:

`
module.exports = {
  verbose: false,
  testTimeout: 6 * 60 * 1000,
  suites: ['test'],
  plugins: {
    sauce: {
      'disabled': true,
      'browsers': [
        {
          'browserName': 'Internet Explorer',
          'platform': 'Windows 10',
          'version': '11'
        },
        {
          'browserName': 'safari',
          'platform': 'OS X 10.11',
          'version': '9.0'
        } ] } }};
`
Contents of `.travis.yml` file:
```yaml
language: node_js
sudo: required
node_js: stable

install:
- npm install
- npm install -g bower
- bower install

before_script:
- gulp lint

script:
- xvfb-run wct --plugin sauce test
notifications:
  flowdock:
    on_failure: change
cache:
  directories:
  - node_modules
```

The output is the following:
Windows 10 Internet Explorer 11 Tests failed: Timed out
OS X 10.11 safari 9.0    Tests failed: Timed out
Test run ended in failure: Timed out
Error: Timed out
